### ISSUE TITLE
17.1.0 is out, care to pull it in?

### ISSUE THREAD

**Issue by salyzyn** [rkel/nrf5sdk#1]
https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v17.x.x/nRF5_SDK_17.1.0_ddde560.zip

**Comment by rkel** [comment]
Hi. I am even surprised that anybody is using that "unofficial" release. It was created as an internal project for my own work that was switched to use NRF Connect SDK. But anyway it is nice to know that anybody else wish to use this kind of release. Please keep in mind that nRF5 SDK has limited support. I will try to add new nRF5 SDK. It should be the case of just replacing the new files. Not sure I will be able to do it today. Rather somewhere in this week.

**Comment by salyzyn** [comment]
Well, there are no official releases on git with the the individual snapshots of releases by nordic semiconductors that I could find other than their tarbal repository. You and Dario Nieuwenhuis (github.com/akiles) appear to be the only two that have taken the effort to snapshot the entire set of tarballs into a git repository that one could use as a submodule in ones project. In an effort to not spin my own and waste space, I figure it is best to use an existing resource such as yours in the future, one or the other, to be used as backup to the other.

Take your time, but it is good to see something on github that could serve use in the public sphere. That is kinda what open source is about :-)

**Comment by rkel** [comment]
Done. Untested - I do not have a project now to test it. But all the files should be here.

**Comment by salyzyn** [comment]
I have used it for a build of some firmware libraries, built as expected as opposed to a zip ball. Like you, have no active projects to test it on iron at the moment though. Thanks!
